# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run tests

on:
  push:
    branches: 'main'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          run_install: true
          version: 8.15.1

      - run: pnpm run lint

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          run_install: true
          version: 8.15.1

      - run: pnpm run build
        env:
          NEXT_PUBLIC_SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pY3N3c2RuaGl4cWpzeGt4cmVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDYwNTM0NDAsImV4cCI6MjAyMTYyOTQ0MH0.PQNQZ0Vf9tASlVXCq1jR-X0wglZRv5vrXFG-FXf8tqM'
          NEXT_PUBLIC_SUPABASE_URL: 'https://nicswsdnhixqjsxkxreg.supabase.co'
